### ISSUE TITLE
What command to use AFTER gvm first runs?

### ISSUE THREAD

**Issue by Davetheraveuk** [AquaL1te/gvm#1]
Hi, I have followed your installation instructions and I am wondering: what command do I enter **after** the first time the program is run as I do not want the gvm docker package to update the database every time I start the gvm docker image.

Thanks.
David.

**Comment by kees-closed** [comment]
Do you mean the [NVT updates](https://github.com/kees-closed/gvm/blob/main/greenbone-feed-sync)? Or do you mean the [database commands](https://github.com/kees-closed/gvm/blob/main/entrypoint.sh#L12-L18)?

If it's about the NVT updates then I can add a conditional based on an environment variable, when set, it will skip the initial NVT sync, which trigger database updates. It will then only be triggered by the daily cron.

If it's about the database commands. Those are idempotent. When already set, it won't have any effect. Unless of course you'll load a new image which has new database commands.

**Comment by kees-closed** [comment]
I created a new image, you can pull it and try it out: `docker pull aqual1te/gvm:v21.04.0-3`

when you use `--env initial_nvt_sync=0`, it should skip the initial NVT syn. More info [here](https://github.com/kees-closed/gvm/blob/main/README.md). Does that solve your issue? If so, then please consider this case closed.

**Comment by Davetheraveuk** [comment]
> --env initial_nvt_sync=0

Thats it! Thats all I needed!
Thanks.
David.
